name: Build Meroy EQ

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel 4

    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MeroyEQ-VST3-Windows
        path: build/MeroyEQ_artefacts/Release/VST3/
